# Generated by Django 4.0.6 on 2024-02-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
